{
    "token": "7db89cdf81f6838e83f82400e817066c",
    "note": null,
    "attributes": {},
    "original_total_price": 1124100,
    "total_price": 1124100,
    "total_discount": 0,
    "total_weight": 900.0,
    "item_count": 9,
    "items": [{
        "id": 42361501384940,
        "properties": {},
        "quantity": 9,
        "variant_id": 42361501384940,
        "key": "42361501384940:a0bbd25eae86322578eacba92d22e521",
        "title": "Natural Astaxanthin 4mg",
        "price": 124900,
        "original_price": 124900,
        "discounted_price": 124900,
        "line_price": 1124100,
        "original_line_price": 1124100,
        "total_discount": 0,
        "discounts": [],
        "sku": "astanatural",
        "grams": 100,
        "vendor": "nacklife",
        "taxable": true,
        "product_id": 7524785422572,
        "product_has_only_default_variant": true,
        "gift_card": false,
        "final_price": 124900,
        "final_line_price": 1124100,
        "url": "\/products\/natural-astaxanthin-4-mg?variant=42361501384940",
        "featured_image": {
            "aspect_ratio": 1.0,
            "alt": "Natural Astaxanthin 4mg",
            "height": 1100,
            "url": "https:\/\/cdn.shopify.com\/s\/files\/1\/0611\/8123\/1340\/products\/asta1.jpg?v=1677335559",
            "width": 1100
        },
        "image": "https:\/\/cdn.shopify.com\/s\/files\/1\/0611\/8123\/1340\/products\/asta1.jpg?v=1677335559",
        "handle": "natural-astaxanthin-4-mg",
        "requires_shipping": true,
        "product_type": "",
        "product_title": "Natural Astaxanthin 4mg",
        "product_description": "\n\n\n\nThe Immunity Boost\nImprove your immunity with nature\u2019s most powerful antioxidant, Astaxanthin.  Natural Astaxanthin\u00a0has a unique molecular structure that makes it literally a hundred times stronger than any other antioxidant. This antioxidant powerhouse helps balance your level of free radicals and combats oxidative stress, thus protecting your body from cell damage and inflammation. The natural Astaxanthin used in Immunity Boost by N\u00e4ck comes from wholly sourced microalgae grown in Sweden and has been extensively studied. Its positive effect on immune system response as well as its ability to support skin health, muscle strength and visual performance is well documented. This ultimate immunity boosting daily supplement helps you stay on top inside out, all year around.\n\n\n\n\n\n\nWHY IMMUNITY BOOST BY N\u00c4CK\nClinically Researched\nThe natural Astaxanthin used in Immunity Boost by N\u00e4ck is cultivated in Sweden by AstaReal. AstaReal\u00b4s high quality natural Astaxanthin is the most studied form of the antioxidant worldwide with a clinical database constituting of 60+ clinical trials and 1400+ participants.\nEvidence Based Benefits\nStrengthens Immune System:\u00a0Astaxanthin has a strong ability to both balance, strengthen and improve the immune system, therefore improving its ability to defend the body whilst also helping to suppress the overactive immune response that creates unwanted inflammation.\u00a0\nSupports Radiant Skin From Within:\u00a0 Astaxanthin can enhance overall skin health by improving skin moisture, elasticity, and reducing UV damage and wrinkles. \u00a0\nImproves Muscle Endurance \u0026 Recovery:\u00a0 Astaxanthin helps reduce muscle damage and improves muscle recovery time after exercise.\nAids Eye Health:\u00a0 A large body of research has shown that astaxanthin supplementation can improve your visual performance and combat eye fatigue and blurred vision. \nNatural, Safe, Effective\nMost clinical research on safety and efficacy with Astaxanthin has been done with doses ranging from 2mg-12mg per day. The general consensus among researchers involved with natural Astaxanthin is that most people derive excellent overall health benefits within this range. Immunity Boost by N\u00e4ck provides 4mg of natural Astaxanthin per capsule. In addition, we use vegan softgel capsules instead of using gelatine from animal sources. So, it\u2019s good for you and the environment! \n\n\n\n\n\n\n\nIMMUNITY BOOST\nWhat\u2019s Inside?\nWe useAstaxanthin \u2013 A naturally occurring carotenoid derived from the microalgae Haematococcus pluvialis.\nWe addVitamin E to preserve the freshness of the capsule and olive oil to support absorption.\nWe stayTruly naked.\n\n\n\n\n\n\n\nDAILY INTAKE\nHow To Use?\nHowTake your Immunity Boost together with food. Astaxanthin is a fat-soluble antioxidant and will absorb more efficiently when combined with a meal.\nRecommended Daily Dose1 capsule a day\n\n\n\n\n\n\n4.7\/5\n\n\n\nShow all reviews\nThe average rating of this product is a whopping 4.7\/5. The secret? Our products are 100% naked. No false claims or hidden agendas. Just carefully selected natural active ingredients.\n\n\nTHE N\u00c4CK COLLECTIVE\nFollow Us On Instagram @nack.life\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n    $(\".testi-slider\").slick({\n      dots: false,\n      arrow:false,\n      infinite: true,\n      autoplay: true,\n  autoplaySpeed: 1000,\n \n     slidesToShow: 3,\n      slidesToScroll: 1,\n      responsive: [\n        {\n          breakpoint: 1024,\n          settings: {\n            slidesToShow: 3,\n            slidesToScroll: 1,\n            infinite: true,\n            dots: true,\n          },\n        },\n        {\n          breakpoint: 600,\n          settings: {\n            slidesToShow: 3,\n            slidesToScroll: 1,\n          },\n        },\n        {\n          breakpoint: 480,\n          settings: {\n            slidesToShow: 2,\n            slidesToScroll: 1,\n          },\n        },\n        \/\/ You can unslick at a given breakpoint now by adding:\n        \/\/ settings: \"unslick\"\n        \/\/ instead of a settings object\n      ],\n    });\n\n  \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nQuestions \u0026 Answers\n\n\n\n\n What is Astaxanthin? \n\nAstaxanthin is the most powerful antioxidant and anti-inflammatory known to science until this moment. Put simply, antioxidants are molecules which hamper the oxidation ( breakdown) of the cells. They are doing this by neutralizing free radicals, and hence provide protection against the damaging effect of these free radicals, which if not balanced leads to oxidation of the cells. The richest source of natural astaxanthin in nature is Haematococcus pluvialis, a microalgae and natural carotenoid that can be found in arctic marine environments and common freshwater rock pools across the world.\n\n\n\n Is Astaxanthin safe to consume by everyone? \n\nAstaxanthin is safe to consume by everyone. However, if you are pregnant, lactating or suffering from any chronic disease you should always consult your doctor before taking any supplements, and that applies to Astaxanthin too.\n\n\n\n Are there any side effects? \n\nDespite being a carotenoid, in mammals astaxanthin does not have any provitamin A activity. Hence it can never be toxic. Studies have proven that supplementation of astaxanthin is safe, and with no significant side effects.\n\n\n\n\n\n\n\n What are the benefits of taking astaxanthin regularly? \n\nAstaxanthin plays a crucial role in our bodies to defend our cells from inflammation and oxidative damage. Various human benefits are recognized to date among others: \u00b7 Improve the immunity response \u00b7 Reduced inflammation \u00b7 Enhanced skin health and protection from UV-damage \u00b7 Increased muscle performance and endurance \u00b7 Better vision\n\n\n\n Can children take astaxanthin? \n\nNo studies of astaxanthin in small children have been conducted and therefore we cannot recommend it as such. However, if your child happens to take the capsules, it is not dangerous or toxic.\n\n\n\n How long shall I take Astaxanthin before I feel or see results? \n\nAstaxanthin takes time to accumulate in the regions of the body where its benefits have been established. Hence clinical studies look at supplementation for a period of at least 4 weeks before re-evaluating the parameters..\n\n\n\n\n\n",
        "variant_title": null,
        "variant_options": ["Default Title"],
        "options_with_values": [{
            "name": "Title",
            "value": "Default Title"
        }],
        "line_level_discount_allocations": [],
        "line_level_total_discount": 0,
        "has_components": false
    }],
    "requires_shipping": true,
    "currency": "INR",
    "items_subtotal_price": 1124100,
    "cart_level_discount_applications": []
}